name: pylinex_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - scipy
  - matplotlib
  - healpy
  - h5py
  - sympy
  - pandas
  - scikit-learn
  - numdifftools
  - pip:
    - git+https://github.com/caden-kunkel/distpy.git
    - git+https://github.com/caden-kunkel/ares.git
    - git+https://github.com/caden-kunkel/perses.git
    - git+https://github.com/caden-kunkel/pylinex.git
